let getVoucherTemplate = (data)=>{
    try{
     let voucherStr = `<ENVELOPE>
     <HEADER>
      <TALLYREQUEST>Import Data</TALLYREQUEST>
     </HEADER>
     <BODY>
      <IMPORTDATA>
       <REQUESTDESC>
        <REPORTNAME>Vouchers</REPORTNAME>
        <STATICVARIABLES>
        </STATICVARIABLES>
       </REQUESTDESC>
       <REQUESTDATA>
        <TALLYMESSAGE xmlns:UDF="TallyUDF">
         <VOUCHER REMOTEID="f654a57e-d3bc-4b86-90f5-28406b2c19ec-00000602" VCHKEY="f654a57e-d3bc-4b86-90f5-28406b2c19ec-0000ac31:00000020" VCHTYPE="Sales" ACTION="Create" OBJVIEW="Invoice Voucher View">
          <BASICBUYERADDRESS.LIST TYPE="String">
           <BASICBUYERADDRESS>${data.billingstreet}</BASICBUYERADDRESS>
           <BASICBUYERADDRESS>${data.billingstate}</BASICBUYERADDRESS>
          </BASICBUYERADDRESS.LIST>
          <OLDAUDITENTRYIDS.LIST TYPE="Number">
           <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
          </OLDAUDITENTRYIDS.LIST>
          <DATE>${data.createddate}</DATE>
          <GUID>f654a57e-d3bc-4b86-90f5-28406b2c19ec-00000602</GUID>
          <VATDEALERTYPE>Regular</VATDEALERTYPE>
          <STATENAME>${data.billingstate}</STATENAME>
          <NARRATION></NARRATION>
          <COUNTRYOFRESIDENCE>${data.billingcountry}</COUNTRYOFRESIDENCE>
          <PARTYGSTIN>${data.member_gst_details__c}</PARTYGSTIN>
          <PLACEOFSUPPLY>${data.billingstate}</PLACEOFSUPPLY>
          <PARTYNAME>${data.name}-${data.member_id__c}</PARTYNAME>
          <PARTYLEDGERNAME>${data.name}-${data.member_id__c}</PARTYLEDGERNAME>
          <VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
          <REFERENCE>${data.receipt_no__c}</REFERENCE>
          <VOUCHERNUMBER>${data.receipt_no__c}</VOUCHERNUMBER>
          <BASICBASEPARTYNAME>${data.name}-${data.member_id__c}</BASICBASEPARTYNAME>
          <CSTFORMISSUETYPE/>
          <CSTFORMRECVTYPE/>
          <FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
          <PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
          <CONSIGNEEGSTIN>${data.member_gst_details__c}</CONSIGNEEGSTIN>
          <BASICBUYERNAME>${data.name}-${data.member_id__c}</BASICBUYERNAME>
          <BASICDATETIMEOFINVOICE>${data.createddate}</BASICDATETIMEOFINVOICE>
          <BASICDATETIMEOFREMOVAL>${data.createddate}</BASICDATETIMEOFREMOVAL>
          <VCHGSTCLASS/>
          <CONSIGNEESTATENAME>${data.billingstate}</CONSIGNEESTATENAME>
          <ENTEREDBY>a</ENTEREDBY>
          <VOUCHERTYPEORIGNAME>Sales</VOUCHERTYPEORIGNAME>
          <DIFFACTUALQTY>No</DIFFACTUALQTY>
          <ISMSTFROMSYNC>No</ISMSTFROMSYNC>
          <ASORIGINAL>No</ASORIGINAL>
          <AUDITED>No</AUDITED>
          <FORJOBCOSTING>No</FORJOBCOSTING>
          <ISOPTIONAL>No</ISOPTIONAL>
          <EFFECTIVEDATE>${data.createddate}</EFFECTIVEDATE>
          <USEFOREXCISE>No</USEFOREXCISE>
          <ISFORJOBWORKIN>No</ISFORJOBWORKIN>
          <ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
          <USEFORINTEREST>No</USEFORINTEREST>
          <USEFORGAINLOSS>No</USEFORGAINLOSS>
          <USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
          <USEFORCOMPOUND>No</USEFORCOMPOUND>
          <USEFORSERVICETAX>No</USEFORSERVICETAX>
          <ISDELETED>No</ISDELETED>
          <ISONHOLD>No</ISONHOLD>
          <ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
          <ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
          <EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
          <USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
          <IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
          <EXCISEOPENING>No</EXCISEOPENING>
          <USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
          <ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
          <ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
          <ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
          <INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
          <ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
          <ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
          <IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
          <ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
          <ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
          <ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
          <ISISDVOUCHER>No</ISISDVOUCHER>
          <ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
          <ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
          <ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
          <GSTNOTEXPORTED>No</GSTNOTEXPORTED>
          <IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
          <ISGSTREFUND>No</ISGSTREFUND>
          <ISGSTSECSEVENAPPLICABLE>No</ISGSTSECSEVENAPPLICABLE>
          <ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
          <ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
          <ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
          <ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
          <ISCANCELLED>No</ISCANCELLED>
          <HASCASHFLOW>No</HASCASHFLOW>
          <ISPOSTDATED>No</ISPOSTDATED>
          <USETRACKINGNUMBER>No</USETRACKINGNUMBER>
          <ISINVOICE>Yes</ISINVOICE>
          <MFGJOURNAL>No</MFGJOURNAL>
          <HASDISCOUNTS>No</HASDISCOUNTS>
          <ASPAYSLIP>No</ASPAYSLIP>
          <ISCOSTCENTRE>No</ISCOSTCENTRE>
          <ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
          <ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
          <ISBLANKCHEQUE>No</ISBLANKCHEQUE>
          <ISVOID>No</ISVOID>
          <ORDERLINESTATUS>No</ORDERLINESTATUS>
          <VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
          <VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
          <ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
          <VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
          <ISVATDUTYPAID>Yes</ISVATDUTYPAID>
          <ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
          <ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
          <CHANGEVCHMODE>No</CHANGEVCHMODE>
          <ALTERID> 3102</ALTERID>
          <MASTERID> 1538</MASTERID>
          <VOUCHERKEY>189326453375008</VOUCHERKEY>
          <EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
          <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
          <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
          <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
          <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
          <DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
          <INVENTORYENTRIES.LIST>      </INVENTORYENTRIES.LIST>
          <SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
          <INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
          <INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
          <INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
          <ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
          <ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
          <INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
          <LEDGERENTRIES.LIST>
           <OLDAUDITENTRYIDS.LIST TYPE="Number">
            <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
           </OLDAUDITENTRYIDS.LIST>
           <LEDGERNAME>${data.name}-${data.member_id__c}</LEDGERNAME>
           <GSTCLASS/>
           <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
           <LEDGERFROMITEM>No</LEDGERFROMITEM>
           <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
           <ISPARTYLEDGER>Yes</ISPARTYLEDGER>
           <ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
           <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
           <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
           <AMOUNT>-${data.grand_total__c}</AMOUNT>
           <VATEXPAMOUNT>-${data.grand_total__c}</VATEXPAMOUNT>
           <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
           <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
           <BILLALLOCATIONS.LIST>
            <NAME>Inv 2</NAME>
            <BILLTYPE>Agst Ref</BILLTYPE>
            <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
            <AMOUNT>-15000.16</AMOUNT>
            <INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
            <STBILLCATEGORIES.LIST>        </STBILLCATEGORIES.LIST>
           </BILLALLOCATIONS.LIST>
           <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
           <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
           <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
           <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
           <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
           <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
           <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
           <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
           <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
           <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
           <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
           <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
           <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
           <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
           <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
           <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
           <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
           <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
           <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
           <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
          </LEDGERENTRIES.LIST>
          <LEDGERENTRIES.LIST>
           <OLDAUDITENTRYIDS.LIST TYPE="Number">
            <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
           </OLDAUDITENTRYIDS.LIST>
           <LEDGERNAME>${data.membership_type_name__c}</LEDGERNAME> 
           <GSTCLASS/>
           <GSTOVRDNTAXABILITY>Taxable</GSTOVRDNTAXABILITY>
           <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
           <LEDGERFROMITEM>No</LEDGERFROMITEM>
           <REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
           <ISPARTYLEDGER>No</ISPARTYLEDGER>
           <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
           <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
           <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
           <AMOUNT>${data.net_amount__c}</AMOUNT>
           <VATEXPAMOUNT>${data.net_amount__c}</VATEXPAMOUNT>
           <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
           <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
           <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
           <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
           <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
           <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
           <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
           <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
           <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
           <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
           <RATEDETAILS.LIST>
            <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
            <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
           </RATEDETAILS.LIST>
           <RATEDETAILS.LIST>
            <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
            <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
           </RATEDETAILS.LIST>
           <RATEDETAILS.LIST>
            <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
            <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
           </RATEDETAILS.LIST>
           <RATEDETAILS.LIST>
            <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
            <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
           </RATEDETAILS.LIST>
           <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
           <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
           <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
           <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
           <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
           <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
           <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
           <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
           <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
           <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
           <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
           <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
           <UDF:USERDESCRIPTION.LIST DESC="User Description" ISLIST="YES" TYPE="String" INDEX="29">
            <UDF:USERDESCRIPTION DESC="User Description">Membership Number: ${data.membership_number__c}</UDF:USERDESCRIPTION>
            <UDF:USERDESCRIPTION DESC="User Description">Payment For: ${data.payment_for__c}</UDF:USERDESCRIPTION>
            <UDF:USERDESCRIPTION DESC="User Description">Payment Mode: ${data.payment_mode__c}</UDF:USERDESCRIPTION>
            <UDF:USERDESCRIPTION DESC="User Description">Payment Name: ${data.receipt_no__c}</UDF:USERDESCRIPTION>
            <UDF:USERDESCRIPTION DESC="User Description">MN Expirty MM-YYYY: ${data.expiry_date__c}</UDF:USERDESCRIPTION>
           </UDF:USERDESCRIPTION.LIST>
          </LEDGERENTRIES.LIST>
          <LEDGERENTRIES.LIST>
           <OLDAUDITENTRYIDS.LIST TYPE="Number">
            <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
           </OLDAUDITENTRYIDS.LIST>
           <LEDGERNAME>SGST</LEDGERNAME>
           <GSTCLASS/>
           <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
           <LEDGERFROMITEM>No</LEDGERFROMITEM>
           <REMOVEZEROENTRIES>Yes</REMOVEZEROENTRIES>
           <ISPARTYLEDGER>No</ISPARTYLEDGER>
           <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
           <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
           <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
           <AMOUNT>${data.SGST}</AMOUNT>
           <VATEXPAMOUNT>${data.SGST}</VATEXPAMOUNT>
           <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
           <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
           <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
           <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
           <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
           <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
           <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
           <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
           <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
           <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
           <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
           <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
           <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
           <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
           <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
           <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
           <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
           <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
           <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
           <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
           <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
           <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
           <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
          </LEDGERENTRIES.LIST>
          <LEDGERENTRIES.LIST>
          <OLDAUDITENTRYIDS.LIST TYPE="Number">
           <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
          </OLDAUDITENTRYIDS.LIST>
          <LEDGERNAME>CGST</LEDGERNAME>
          <GSTCLASS/>
          <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
          <LEDGERFROMITEM>No</LEDGERFROMITEM>
          <REMOVEZEROENTRIES>Yes</REMOVEZEROENTRIES>
          <ISPARTYLEDGER>No</ISPARTYLEDGER>
          <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
          <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
          <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
          <AMOUNT>${data.CGST}</AMOUNT>
          <VATEXPAMOUNT>${data.CGST}</VATEXPAMOUNT>
          <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
          <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
          <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
          <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
          <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
          <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
          <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
          <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
          <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
          <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
          <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
          <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
          <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
          <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
          <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
          <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
          <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
          <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
          <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
          <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
          <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
          <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
          <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
         </LEDGERENTRIES.LIST>
             <LEDGERENTRIES.LIST>
           <OLDAUDITENTRYIDS.LIST TYPE="Number">
            <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
           </OLDAUDITENTRYIDS.LIST>
           <LEDGERNAME>IGST</LEDGERNAME>
           <GSTCLASS/>
           <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
           <LEDGERFROMITEM>No</LEDGERFROMITEM>
           <REMOVEZEROENTRIES>Yes</REMOVEZEROENTRIES>
           <ISPARTYLEDGER>No</ISPARTYLEDGER>
           <ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
           <ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
           <ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
           <AMOUNT>${data.IGST}</AMOUNT>
           <VATEXPAMOUNT>${data.IGST}</VATEXPAMOUNT>
           <SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
           <BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
           <BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
           <INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
           <OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
           <ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
           <AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
           <INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
           <DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
           <EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
           <RATEDETAILS.LIST>       </RATEDETAILS.LIST>
           <SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
           <STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
           <EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
           <TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
           <TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
           <TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
           <VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
           <COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
           <REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
           <INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
           <VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
           <ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
          </LEDGERENTRIES.LIST>
          <PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
          <ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
          <GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>
          <GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>
          <TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
         </VOUCHER>
        </TALLYMESSAGE>
       </REQUESTDATA>
      </IMPORTDATA>
     </BODY>
    </ENVELOPE>`
    return voucherStr
    }catch(e){
        return ``
    }
}
module.exports={
    getVoucherTemplate
}