let getStaticLedgerTemplate = (data)=>{
    try{
            let template= `<ENVELOPE>
            <HEADER>
             <TALLYREQUEST>Import Data</TALLYREQUEST>
            </HEADER>
            <BODY>
             <IMPORTDATA>
              <REQUESTDESC>
               <REPORTNAME>All Masters</REPORTNAME>
               <STATICVARIABLES>
                <SVCURRENTCOMPANY>${data.supplier_company}</SVCURRENTCOMPANY>
               </STATICVARIABLES>
              </REQUESTDESC>
              <REQUESTDATA>
               <TALLYMESSAGE xmlns:UDF="TallyUDF">
                <CURRENCY NAME="₹" RESERVEDNAME="">
                 <MAILINGNAME>INR</MAILINGNAME>
                 <ORIGINALNAME>₹</ORIGINALNAME>
                 <EXPANDEDSYMBOL>INR</EXPANDEDSYMBOL>
                 <DECIMALSYMBOL>paise</DECIMALSYMBOL>
                 <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
                 <ASORIGINAL>Yes</ASORIGINAL>
                 <ISSUFFIX>No</ISSUFFIX>
                 <HASSPACE>Yes</HASSPACE>
                 <INMILLIONS>No</INMILLIONS>
                 <ALTERID> 344</ALTERID>
                 <DECIMALPLACES> 2</DECIMALPLACES>
                 <DECIMALPLACESFORPRINTING> 2</DECIMALPLACESFORPRINTING>
                 <DAILYSTDRATES.LIST>      </DAILYSTDRATES.LIST>
                 <DAILYBUYINGRATES.LIST>      </DAILYBUYINGRATES.LIST>
                 <DAILYSELLINGRATES.LIST>      </DAILYSELLINGRATES.LIST>
                </CURRENCY>
               </TALLYMESSAGE>
               <TALLYMESSAGE xmlns:UDF="TallyUDF">
                <CURRENCY NAME="₹" RESERVEDNAME="">
                 <GUID>0ac9cccf-c451-4ff6-9bdc-9eb0dafefea9-0000001d</GUID>
                 <MAILINGNAME>INR</MAILINGNAME>
                 <ORIGINALNAME>₹</ORIGINALNAME>
                 <EXPANDEDSYMBOL>INR</EXPANDEDSYMBOL>
                 <DECIMALSYMBOL>paise</DECIMALSYMBOL>
                 <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
                 <ASORIGINAL>Yes</ASORIGINAL>
                 <ISSUFFIX>No</ISSUFFIX>
                 <HASSPACE>Yes</HASSPACE>
                 <INMILLIONS>No</INMILLIONS>
                 <ALTERID> 344</ALTERID>
                 <DECIMALPLACES> 2</DECIMALPLACES>
                 <DECIMALPLACESFORPRINTING> 2</DECIMALPLACESFORPRINTING>
                 <DAILYSTDRATES.LIST>      </DAILYSTDRATES.LIST>
                 <DAILYBUYINGRATES.LIST>      </DAILYBUYINGRATES.LIST>
                 <DAILYSELLINGRATES.LIST>      </DAILYSELLINGRATES.LIST>
                </CURRENCY>
               </TALLYMESSAGE>
               <TALLYMESSAGE xmlns:UDF="TallyUDF">
                <GROUP NAME="${data.property_name}" RESERVEDNAME="">
                 <GUID>0ac9cccf-c451-4ff6-9bdc-9eb0dafefea9-000000bd</GUID>
                 <PARENT>Club Marriott</PARENT>
                 <BASICGROUPISCALCULABLE>No</BASICGROUPISCALCULABLE>
                 <ADDLALLOCTYPE/>
                 <GRPDEBITPARENT/>
                 <GRPCREDITPARENT/>
                 <ISBILLWISEON>No</ISBILLWISEON>
                 <ISCOSTCENTRESON>Yes</ISCOSTCENTRESON>
                 <ISADDABLE>No</ISADDABLE>
                 <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
                 <ASORIGINAL>Yes</ASORIGINAL>
                 <ISSUBLEDGER>No</ISSUBLEDGER>
                 <ISREVENUE>No</ISREVENUE>
                 <AFFECTSGROSSPROFIT>No</AFFECTSGROSSPROFIT>
                 <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
                 <TRACKNEGATIVEBALANCES>Yes</TRACKNEGATIVEBALANCES>
                 <ISCONDENSED>No</ISCONDENSED>
                 <AFFECTSSTOCK>No</AFFECTSSTOCK>
                 <ISGROUPFORLOANRCPT>No</ISGROUPFORLOANRCPT>
                 <ISGROUPFORLOANPYMNT>No</ISGROUPFORLOANPYMNT>
                 <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
                 <ISINVDETAILSENABLE>No</ISINVDETAILSENABLE>
                 <SORTPOSITION> 500</SORTPOSITION>
                 <ALTERID> 281</ALTERID>
                 <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
                 <VATDETAILS.LIST>      </VATDETAILS.LIST>
                 <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
                 <GSTDETAILS.LIST>      </GSTDETAILS.LIST>
                 <LANGUAGENAME.LIST>
                  <NAME.LIST TYPE="String">
                   <NAME>${data.property_name}</NAME>
                  </NAME.LIST>
                  <LANGUAGEID> 1033</LANGUAGEID>
                 </LANGUAGENAME.LIST>
                 <XBRLDETAIL.LIST>      </XBRLDETAIL.LIST>
                 <AUDITDETAILS.LIST>      </AUDITDETAILS.LIST>
                 <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
                 <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
                 <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
                 <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
                 <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
                 <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
                </GROUP>
               </TALLYMESSAGE>
               <TALLYMESSAGE xmlns:UDF="TallyUDF">
                <LEDGER NAME="${data.name}" RESERVEDNAME="">
                 <MAILINGNAME.LIST TYPE="String">
                  <MAILINGNAME>${data.name}</MAILINGNAME>
                 </MAILINGNAME.LIST>
                 <OLDAUDITENTRYIDS.LIST TYPE="Number">
                  <OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
                 </OLDAUDITENTRYIDS.LIST>
                 <GUID>0ac9cccf-c451-4ff6-9bdc-9eb0dafefea9-000000d4</GUID>
                 <CURRENCYNAME>₹</CURRENCYNAME>
                 <PARENT>${data.property_name}</PARENT>
                 <GSTAPPLICABLE></GSTAPPLICABLE>
                 <TAXCLASSIFICATIONNAME/>
                 <TAXTYPE>Others</TAXTYPE>
                 <LEDADDLALLOCTYPE/>
                 <GSTTYPE/>
                 <APPROPRIATEFOR/>
                 <GSTTYPEOFSUPPLY>Services</GSTTYPEOFSUPPLY>
                 <SERVICECATEGORY></SERVICECATEGORY>
                 <EXCISELEDGERCLASSIFICATION/>
                 <EXCISEDUTYTYPE/>
                 <EXCISENATUREOFPURCHASE/>
                 <LEDGERFBTCATEGORY/>
                 <VATAPPLICABLE></VATAPPLICABLE>
                 <ISBILLWISEON>No</ISBILLWISEON>
                 <ISCOSTCENTRESON>Yes</ISCOSTCENTRESON>
                 <ISINTERESTON>No</ISINTERESTON>
                 <ALLOWINMOBILE>No</ALLOWINMOBILE>
                 <ISCOSTTRACKINGON>No</ISCOSTTRACKINGON>
                 <ISBENEFICIARYCODEON>No</ISBENEFICIARYCODEON>
                 <ISEXPORTONVCHCREATE>No</ISEXPORTONVCHCREATE>
                 <PLASINCOMEEXPENSE>No</PLASINCOMEEXPENSE>
                 <ISUPDATINGTARGETID>No</ISUPDATINGTARGETID>
                 <ASORIGINAL>Yes</ASORIGINAL>
                 <ISCONDENSED>No</ISCONDENSED>
                 <AFFECTSSTOCK>No</AFFECTSSTOCK>
                 <ISRATEINCLUSIVEVAT>No</ISRATEINCLUSIVEVAT>
                 <FORPAYROLL>No</FORPAYROLL>
                 <ISABCENABLED>No</ISABCENABLED>
                 <ISCREDITDAYSCHKON>No</ISCREDITDAYSCHKON>
                 <INTERESTONBILLWISE>No</INTERESTONBILLWISE>
                 <OVERRIDEINTEREST>No</OVERRIDEINTEREST>
                 <OVERRIDEADVINTEREST>No</OVERRIDEADVINTEREST>
                 <USEFORVAT>No</USEFORVAT>
                 <IGNORETDSEXEMPT>No</IGNORETDSEXEMPT>
                 <ISTCSAPPLICABLE>No</ISTCSAPPLICABLE>
                 <ISTDSAPPLICABLE>No</ISTDSAPPLICABLE>
                 <ISFBTAPPLICABLE>No</ISFBTAPPLICABLE>
                 <ISGSTAPPLICABLE>No</ISGSTAPPLICABLE>
                 <ISEXCISEAPPLICABLE>No</ISEXCISEAPPLICABLE>
                 <ISTDSEXPENSE>No</ISTDSEXPENSE>
                 <ISEDLIAPPLICABLE>No</ISEDLIAPPLICABLE>
                 <ISRELATEDPARTY>No</ISRELATEDPARTY>
                 <USEFORESIELIGIBILITY>No</USEFORESIELIGIBILITY>
                 <ISINTERESTINCLLASTDAY>No</ISINTERESTINCLLASTDAY>
                 <APPROPRIATETAXVALUE>No</APPROPRIATETAXVALUE>
                 <ISBEHAVEASDUTY>No</ISBEHAVEASDUTY>
                 <INTERESTINCLDAYOFADDITION>No</INTERESTINCLDAYOFADDITION>
                 <INTERESTINCLDAYOFDEDUCTION>No</INTERESTINCLDAYOFDEDUCTION>
                 <ISOTHTERRITORYASSESSEE>No</ISOTHTERRITORYASSESSEE>
                 <IGNOREMISMATCHWITHWARNING>No</IGNOREMISMATCHWITHWARNING>
                 <USEASNOTIONALBANK>No</USEASNOTIONALBANK>
                 <OVERRIDECREDITLIMIT>No</OVERRIDECREDITLIMIT>
                 <ISAGAINSTFORMC>No</ISAGAINSTFORMC>
                 <ISCHEQUEPRINTINGENABLED>Yes</ISCHEQUEPRINTINGENABLED>
                 <ISPAYUPLOAD>No</ISPAYUPLOAD>
                 <ISPAYBATCHONLYSAL>No</ISPAYBATCHONLYSAL>
                 <ISBNFCODESUPPORTED>No</ISBNFCODESUPPORTED>
                 <ALLOWEXPORTWITHERRORS>No</ALLOWEXPORTWITHERRORS>
                 <CONSIDERPURCHASEFOREXPORT>No</CONSIDERPURCHASEFOREXPORT>
                 <ISTRANSPORTER>No</ISTRANSPORTER>
                 <USEFORNOTIONALITC>No</USEFORNOTIONALITC>
                 <ISECOMMOPERATOR>No</ISECOMMOPERATOR>
                 <SHOWINPAYSLIP>No</SHOWINPAYSLIP>
                 <USEFORGRATUITY>No</USEFORGRATUITY>
                 <ISTDSPROJECTED>No</ISTDSPROJECTED>
                 <FORSERVICETAX>No</FORSERVICETAX>
                 <ISINPUTCREDIT>No</ISINPUTCREDIT>
                 <ISEXEMPTED>No</ISEXEMPTED>
                 <ISABATEMENTAPPLICABLE>No</ISABATEMENTAPPLICABLE>
                 <ISSTXPARTY>No</ISSTXPARTY>
                 <ISSTXNONREALIZEDTYPE>No</ISSTXNONREALIZEDTYPE>
                 <ISUSEDFORCVD>No</ISUSEDFORCVD>
                 <LEDBELONGSTONONTAXABLE>No</LEDBELONGSTONONTAXABLE>
                 <ISEXCISEMERCHANTEXPORTER>No</ISEXCISEMERCHANTEXPORTER>
                 <ISPARTYEXEMPTED>No</ISPARTYEXEMPTED>
                 <ISSEZPARTY>No</ISSEZPARTY>
                 <TDSDEDUCTEEISSPECIALRATE>No</TDSDEDUCTEEISSPECIALRATE>
                 <ISECHEQUESUPPORTED>No</ISECHEQUESUPPORTED>
                 <ISEDDSUPPORTED>No</ISEDDSUPPORTED>
                 <HASECHEQUEDELIVERYMODE>No</HASECHEQUEDELIVERYMODE>
                 <HASECHEQUEDELIVERYTO>No</HASECHEQUEDELIVERYTO>
                 <HASECHEQUEPRINTLOCATION>No</HASECHEQUEPRINTLOCATION>
                 <HASECHEQUEPAYABLELOCATION>No</HASECHEQUEPAYABLELOCATION>
                 <HASECHEQUEBANKLOCATION>No</HASECHEQUEBANKLOCATION>
                 <HASEDDDELIVERYMODE>No</HASEDDDELIVERYMODE>
                 <HASEDDDELIVERYTO>No</HASEDDDELIVERYTO>
                 <HASEDDPRINTLOCATION>No</HASEDDPRINTLOCATION>
                 <HASEDDPAYABLELOCATION>No</HASEDDPAYABLELOCATION>
                 <HASEDDBANKLOCATION>No</HASEDDBANKLOCATION>
                 <ISEBANKINGENABLED>No</ISEBANKINGENABLED>
                 <ISEXPORTFILEENCRYPTED>No</ISEXPORTFILEENCRYPTED>
                 <ISBATCHENABLED>No</ISBATCHENABLED>
                 <ISPRODUCTCODEBASED>No</ISPRODUCTCODEBASED>
                 <HASEDDCITY>No</HASEDDCITY>
                 <HASECHEQUECITY>No</HASECHEQUECITY>
                 <ISFILENAMEFORMATSUPPORTED>No</ISFILENAMEFORMATSUPPORTED>
                 <HASCLIENTCODE>No</HASCLIENTCODE>
                 <PAYINSISBATCHAPPLICABLE>No</PAYINSISBATCHAPPLICABLE>
                 <PAYINSISFILENUMAPP>No</PAYINSISFILENUMAPP>
                 <ISSALARYTRANSGROUPEDFORBRS>No</ISSALARYTRANSGROUPEDFORBRS>
                 <ISEBANKINGSUPPORTED>No</ISEBANKINGSUPPORTED>
                 <ISSCBUAE>No</ISSCBUAE>
                 <ISBANKSTATUSAPP>No</ISBANKSTATUSAPP>
                 <ISSALARYGROUPED>No</ISSALARYGROUPED>
                 <USEFORPURCHASETAX>No</USEFORPURCHASETAX>
                 <AUDITED>No</AUDITED>
                 <SORTPOSITION> 1000</SORTPOSITION>
                 <ALTERID> 348</ALTERID>
                 <SERVICETAXDETAILS.LIST>      </SERVICETAXDETAILS.LIST>
                 <LBTREGNDETAILS.LIST>      </LBTREGNDETAILS.LIST>
                 <VATDETAILS.LIST>      </VATDETAILS.LIST>
                 <SALESTAXCESSDETAILS.LIST>      </SALESTAXCESSDETAILS.LIST>
                 <GSTDETAILS.LIST>
                  <APPLICABLEFROM>20170701</APPLICABLEFROM>
                  <HSNCODE>999599</HSNCODE>
                  <HSNMASTERNAME/>
                  <TAXABILITY/>
                  <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
                  <ISNONGSTGOODS>No</ISNONGSTGOODS>
                  <GSTINELIGIBLEITC>No</GSTINELIGIBLEITC>
                  <INCLUDEEXPFORSLABCALC>No</INCLUDEEXPFORSLABCALC>
                  <STATEWISEDETAILS.LIST>
                   <STATENAME></STATENAME>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Cess on Qty</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Quantity</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>State Cess</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <GSTSLABRATES.LIST>        </GSTSLABRATES.LIST>
                  </STATEWISEDETAILS.LIST>
                  <TEMPGSTDETAILSLABRATES.LIST>       </TEMPGSTDETAILSLABRATES.LIST>
                 </GSTDETAILS.LIST>
                 <GSTDETAILS.LIST>
                  <APPLICABLEFROM>20210322</APPLICABLEFROM>
                  <HSNCODE>999599</HSNCODE>
                  <HSNMASTERNAME/>
                  <TAXABILITY>Taxable</TAXABILITY>
                  <ISREVERSECHARGEAPPLICABLE>No</ISREVERSECHARGEAPPLICABLE>
                  <ISNONGSTGOODS>No</ISNONGSTGOODS>
                  <GSTINELIGIBLEITC>No</GSTINELIGIBLEITC>
                  <INCLUDEEXPFORSLABCALC>No</INCLUDEEXPFORSLABCALC>
                  <STATEWISEDETAILS.LIST>
                   <STATENAME></STATENAME>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Central Tax</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                    <GSTRATE> 9</GSTRATE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>State Tax</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                    <GSTRATE> 9</GSTRATE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Integrated Tax</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                    <GSTRATE> 18</GSTRATE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Cess</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>Cess on Qty</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Quantity</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <RATEDETAILS.LIST>
                    <GSTRATEDUTYHEAD>State Cess</GSTRATEDUTYHEAD>
                    <GSTRATEVALUATIONTYPE>Based on Value</GSTRATEVALUATIONTYPE>
                   </RATEDETAILS.LIST>
                   <GSTSLABRATES.LIST>        </GSTSLABRATES.LIST>
                  </STATEWISEDETAILS.LIST>
                  <TEMPGSTDETAILSLABRATES.LIST>       </TEMPGSTDETAILSLABRATES.LIST>
                 </GSTDETAILS.LIST>
                 <LANGUAGENAME.LIST>
                  <NAME.LIST TYPE="String">
                   <NAME>${data.name}</NAME>
                  </NAME.LIST>
                  <LANGUAGEID> 1033</LANGUAGEID>
                 </LANGUAGENAME.LIST>
                 <XBRLDETAIL.LIST>      </XBRLDETAIL.LIST>
                 <AUDITDETAILS.LIST>      </AUDITDETAILS.LIST>
                 <SCHVIDETAILS.LIST>      </SCHVIDETAILS.LIST>
                 <EXCISETARIFFDETAILS.LIST>      </EXCISETARIFFDETAILS.LIST>
                 <TCSCATEGORYDETAILS.LIST>      </TCSCATEGORYDETAILS.LIST>
                 <TDSCATEGORYDETAILS.LIST>      </TDSCATEGORYDETAILS.LIST>
                 <SLABPERIOD.LIST>      </SLABPERIOD.LIST>
                 <GRATUITYPERIOD.LIST>      </GRATUITYPERIOD.LIST>
                 <ADDITIONALCOMPUTATIONS.LIST>      </ADDITIONALCOMPUTATIONS.LIST>
                 <EXCISEJURISDICTIONDETAILS.LIST>      </EXCISEJURISDICTIONDETAILS.LIST>
                 <EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
                 <BANKALLOCATIONS.LIST>      </BANKALLOCATIONS.LIST>
                 <PAYMENTDETAILS.LIST>      </PAYMENTDETAILS.LIST>
                 <BANKEXPORTFORMATS.LIST>      </BANKEXPORTFORMATS.LIST>
                 <BILLALLOCATIONS.LIST>      </BILLALLOCATIONS.LIST>
                 <INTERESTCOLLECTION.LIST>      </INTERESTCOLLECTION.LIST>
                 <LEDGERCLOSINGVALUES.LIST>      </LEDGERCLOSINGVALUES.LIST>
                 <LEDGERAUDITCLASS.LIST>      </LEDGERAUDITCLASS.LIST>
                 <OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
                 <TDSEXEMPTIONRULES.LIST>      </TDSEXEMPTIONRULES.LIST>
                 <DEDUCTINSAMEVCHRULES.LIST>      </DEDUCTINSAMEVCHRULES.LIST>
                 <LOWERDEDUCTION.LIST>      </LOWERDEDUCTION.LIST>
                 <STXABATEMENTDETAILS.LIST>      </STXABATEMENTDETAILS.LIST>
                 <LEDMULTIADDRESSLIST.LIST>      </LEDMULTIADDRESSLIST.LIST>
                 <STXTAXDETAILS.LIST>      </STXTAXDETAILS.LIST>
                 <CHEQUERANGE.LIST>      </CHEQUERANGE.LIST>
                 <DEFAULTVCHCHEQUEDETAILS.LIST>      </DEFAULTVCHCHEQUEDETAILS.LIST>
                 <ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
                 <AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
                 <BRSIMPORTEDINFO.LIST>      </BRSIMPORTEDINFO.LIST>
                 <AUTOBRSCONFIGS.LIST>      </AUTOBRSCONFIGS.LIST>
                 <BANKURENTRIES.LIST>      </BANKURENTRIES.LIST>
                 <DEFAULTCHEQUEDETAILS.LIST>      </DEFAULTCHEQUEDETAILS.LIST>
                 <DEFAULTOPENINGCHEQUEDETAILS.LIST>      </DEFAULTOPENINGCHEQUEDETAILS.LIST>
                 <CANCELLEDPAYALLOCATIONS.LIST>      </CANCELLEDPAYALLOCATIONS.LIST>
                 <ECHEQUEPRINTLOCATION.LIST>      </ECHEQUEPRINTLOCATION.LIST>
                 <ECHEQUEPAYABLELOCATION.LIST>      </ECHEQUEPAYABLELOCATION.LIST>
                 <EDDPRINTLOCATION.LIST>      </EDDPRINTLOCATION.LIST>
                 <EDDPAYABLELOCATION.LIST>      </EDDPAYABLELOCATION.LIST>
                 <AVAILABLETRANSACTIONTYPES.LIST>      </AVAILABLETRANSACTIONTYPES.LIST>
                 <LEDPAYINSCONFIGS.LIST>      </LEDPAYINSCONFIGS.LIST>
                 <TYPECODEDETAILS.LIST>      </TYPECODEDETAILS.LIST>
                 <FIELDVALIDATIONDETAILS.LIST>      </FIELDVALIDATIONDETAILS.LIST>
                 <INPUTCRALLOCS.LIST>      </INPUTCRALLOCS.LIST>
                 <GSTCLASSFNIGSTRATES.LIST>      </GSTCLASSFNIGSTRATES.LIST>
                 <EXTARIFFDUTYHEADDETAILS.LIST>      </EXTARIFFDUTYHEADDETAILS.LIST>
                 <VOUCHERTYPEPRODUCTCODES.LIST>      </VOUCHERTYPEPRODUCTCODES.LIST>
                </LEDGER>
               </TALLYMESSAGE>
               <TALLYMESSAGE xmlns:UDF="TallyUDF">
                <COMPANY>
                 <REMOTECMPINFO.LIST MERGE="Yes">
                  <NAME>0ac9cccf-c451-4ff6-9bdc-9eb0dafefea9</NAME>
                  <REMOTECMPNAME>${data.supplier_company}</REMOTECMPNAME>
                  <REMOTECMPSTATE>${data.state__c}</REMOTECMPSTATE>
                 </REMOTECMPINFO.LIST>
                 <REMOTECMPINFO.LIST MERGE="Yes">
                  <NAME>3105d5c9-a08f-4500-bde5-5b998bc7e009</NAME>
                  <REMOTECMPNAME>${data.supplier_company}</REMOTECMPNAME>
                  <REMOTECMPSTATE>${data.state__c}</REMOTECMPSTATE>
                 </REMOTECMPINFO.LIST>
                </COMPANY>
               </TALLYMESSAGE>
              </REQUESTDATA>
             </IMPORTDATA>
            </BODY>
           </ENVELOPE>
           
           `
           return template
    }catch(e){
        return ``
    }
}


module.exports = {
    getStaticLedgerTemplate
}